# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dental-officeassistant-dpalma-appservice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install, build, and test
        working-directory: starter/ContosoDentistryChatBot/
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_MicrosoftAppId: ${{ secrets.MICROSOFTAPPID }}
          envkey_MicrosoftAppPassword: ${{ secrets.MICROSOFTAPPPASSWORD }}
          envkey_QnAKnowledgebaseId: ${{ secrets.QNAKNOWLEDGEBASEID }}
          envkey_QnAAuthKey: ${{ secrets.QNAAUTHKEY }}
          envkey_QnAEndpointHostName: ${{ secrets.QNAENDPOINTHOSTNAME }}
          envkey_LuisAppId: ${{ secrets.LUISAPPID }}
          envkey_LuisAPIKey: ${{ secrets.LUISAPIKEY }}
          envkey_LuisAPIHostName: ${{ secrets.LUISAPIHOSTNAME }}
          envkey_SchedulerEndpoint: ${{ secrets.SCHEDULERENDPOINT }}
          directory: starter/ContosoDentistryChatBot/
          file_name: .env
          fail_on_empty: false

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: starter/ContosoDentistryChatBot/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dental-officeassistant-dpalma-appservice'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F59DDECC97AD495D88AB35052FB8EC83 }}
          package: .
